services:
  nginx:
    image: nginx:stable-alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-gateway-network
    depends_on:
      crear-personas:
        condition: service_started
      modificar-personas:
        condition: service_started
      consultar-personas: 
        condition: service_started
      borrar-personas:
        condition: service_started
      logs-personas:
        condition: service_started

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/.env:/app/.env
    environment:
      - REACT_APP_API_URL=http://localhost
    networks:
      - api-gateway-network
    depends_on:
      - nginx
 
  # Microservicio: Crear Personas
  crear-personas:
    build: 
      context: ./services/crear-personas
      dockerfile: Dockerfile
    container_name: crear-personas
    volumes:
      - ./services/crear-personas/src:/app/src
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gestion_datos
    networks:
      - api-gateway-network

  # Microservicio: Modificar Personas
  modificar-personas:
    build:
      context: ./services/modificar-personas
      dockerfile: Dockerfile
    container_name: modificar-personas
    volumes:
      - ./services/modificar-personas/src:/app/src
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gestion_datos
    networks:
      - api-gateway-network

  # Microservicio: Consultar Personas (escalable)
  consultar-personas:
    build:
      context: ./services/consultar-personas
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - ./services/consultar-personas/src:/app/src
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gestion_datos
    networks:
      - api-gateway-network

  # Microservicio: Borrar Personas
  borrar-personas:
    build:
      context: ./services/borrar-personas
      dockerfile: Dockerfile
    container_name: borrar-personas
    volumes:
      - ./services/borrar-personas/src:/app/src
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gestion_datos
    networks:
      - api-gateway-network

  # Microservicio: Logs
  logs-personas:
    build:
      context: ./services/logs-personas
      dockerfile: Dockerfile
    container_name: logs-personas
    volumes:
      - ./services/logs-personas/src:/app/src
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gestion_datos
    networks:
      - api-gateway-network

  # Base de datos compartida
  postgres-db:
    build: 
      context: ./services/postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestion_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - api-gateway-network

volumes:
  postgres_data:
    driver: local

networks:
  api-gateway-network:
    driver: bridge


